### ISSUE TITLE
perf: connectivity performance improvement

### ISSUE THREAD

**Issue by geolffreym** [WatchItDev/watchit-app#172]
We have a problem of interoperability between web <=> desktop. 
Since web cannot connect direct with TCP some extra "proxy steps" are needed to achieve interoperability between both envs in the current approach.
We can favor interoperability using exclusive js-ipfs  (waiting for orbit to support [helia](https://github.com/ipfs/helia))

**Comment by bennukem** [comment]
These proxy steps are already well know ? I can't find what needed ?

**Comment by geolffreym** [comment]
Currently our proxy (eg. nginx) opens a websocket connection and redirects wss:// connections coming from the web environments, to an IPFS node, this node is connected to an orbitdb instance that keeps a copy of the metadata "pinned". Let's say it's something like a kind of mirroring, which we think is centralized and doesn't scale.
