### ISSUE TITLE
Stuck on connecting

### ISSUE THREAD

**Issue by dillfrescott** [WatchItDev/watchit-app#177]
I've waited a while and its not doing anything :(

**Comment by dillfrescott** [comment]
Okay

**Comment by dillfrescott** [comment]
Pretty sure this is still an issue Bot lol

**Comment by geolffreym** [comment]
@dillfrescott definetly isn't . Thank you!!

**Comment by geolffreym** [comment]
fixed in v1.0.0-beta.0

**Comment by dillfrescott** [comment]
Excellent!
